# hello-go-deploy-gke task-build-push.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: hello-go-deploy-gke

outputs:
- name: dist

run:
  path: ./hello-go-deploy-gke/ci/scripts/build-push.sh
  # args: [-debug]

