# hello-go-deploy-gke task-deploy.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.11

params:
  GCP_JEFFS_APP_SERVICE_ACCOUNT_FILE: "this will be overwritten"
  GCP_JEFFS_APP_SERVICE_ACCOUNT_EMAIL_ADDRESS: "this will be overwritten"
  GCP_JEFFS_PROJECT_ID: "this will be overwritten"

inputs:
- name: hello-go-deploy-gke

run:
  path: ./hello-go-deploy-gke/ci/scripts/deploy.sh
  # args: [-debug]

