# hello-go-deploy-gke pipeline.yml

jobs:

- name: job-deploy
  plan:
    - get: hello-go-deploy-gke
      trigger: true
    - put: resource-slack-alert
      params:
        channel: '#jeff-builds'
        text: "From hello-go-deploy-gke: STARTED job-deploy in concourse ci."
    - put: resource-repo-status
      params: { state: "pending", description: "STARTED job-deploy in concourse ci.", commit: "hello-go-deploy-gke" }
    - task: task-deploy
      file: hello-go-deploy-gke/ci/tasks/task-deploy.yml
      on_success:
        do:
        - put: resource-slack-alert
          params:
            channel: '#jeff-builds'
            text: "From hello-go-deploy-gke: PASSED job-deploy in concourse ci."
        - put: resource-repo-status
          params: { state: "success", description: "PASSED job-deploy in concourse ci.", commit: "hello-go-deploy-gke" }
      on_failure:
        do:
        - put: resource-slack-alert
          params:
            channel: '#jeff-builds'
            text: "From hello-go-deploy-gke: FAILED job-deploy in concourse ci."
        - put: resource-repo-status
          params: { state: "failure", description: "FAILED job-deploy in concourse ci.", commit: "hello-go-deploy-gke" }

resource_types:

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
- name: github-status
  type: docker-image
  source:
    repository: dpb587/github-status-resource
    tag: master

resources:

- name: hello-go-deploy-gke
  type: git
  source:
    #uri: https://github.com/jeffdecola/hello-go-deploy-gke
    uri: git@github.com:jeffdecola/hello-go-deploy-gke.git
    branch: master
    private_key: {{git_private_key}}
- name: resource-slack-alert
  type: slack-notification
  source:
    url: {{slack_url}} 
- name: resource-repo-status 
  type: github-status
  source:
    repository: jeffdecola/hello-go-deploy-gke 
    access_token: {{repo_github_token}}
    